### ISSUE TITLE
Is not showing full range requested

### ISSUE THREAD

**Issue by Luke2791** [rmellmer/obsidian-link-range#13]
Great plug-in idea and very applicable to me. However, I have run into some issues. For example, if I do ![[John#1:1..2:2]] it will give me 1:1-2:1, and then repeat verses 1:1-2:2. It looks like it is getting cut off or that there is some kind of maximum internal link preview size that is being exceeding. only thing is, this happens regardless of the length past a certain point... 

Secondly - and I saw someone submit this, it would be wonderful to be able to preview the headers twice. Right now it only shows the header, but not the second.

Lastly, there seems to be a strange bug where the # and .. switch back and forth. I.e sometimes it looks like ![[John..1:1..2:2]] instead of ![[John#1:1..2:2]]. Thanks so much for taking the time to make this plug in - regardless of how far you go with it!

**Comment by WalkBySight599** [comment]
Did you ever get this to work? I also opened an issue

**Comment by Luke2791** [comment]
I never got it to work. I believe I deactivated / turned off the plug in and am pursuing a different route now. Feel free to let me know if you get it figured out!

**Comment by WalkBySight599** [comment]
I'm curious to see what route you went. My main goal is a simple popup to
read a verse range in my articles. I made an API that worked, but it ended
up calling to much, I thought about trying to make a plugin.

**Comment by Luke2791** [comment]
Check out the "Bible Reference" plug in. It's excellent and is great for scripture reference. Beyond that, if you put full texts (i.e. the book of John) in your vault, you can use headings to insert partial parts of books/chapters/sections in your other notes, etc. For example `![[John#Chapter1]]`
