### ISSUE TITLE
Unable to find section

### ISSUE THREAD

**Issue by acepelon** [rmellmer/obsidian-link-range#3]
Hi there!   I was trying out this plugin, grabbing the manifest.json and main.js from here: https://github.com/rmellmer/obsidian-link-range/releases/tag/1.0.0

and when I go to create a range, I am getting:

![CleanShot 2023-03-18 at 22 28 36](https://user-images.githubusercontent.com/954789/226152012-82bcfb1e-6a08-4d3f-8174-9cb549b9f746.jpg)
---
You can see my test page here:
![CleanShot 2023-03-18 at 22 29 41](https://user-images.githubusercontent.com/954789/226152036-233dd528-2b43-49f1-896a-2c73e02261dc.jpg)
---

Am I just doing something wrong?  I have tried with a few different separators, but I have this one configured now since that is the one shown in your example:
![CleanShot 2023-03-18 at 22 30 47](https://user-images.githubusercontent.com/954789/226152064-f528a465-c0d1-4e2d-9f94-b410cf61e59a.jpg)
---
I was really looking for some way to do this range linking where the links would show up with the Strange New Worlds integration, but I got stuck here with the other similar plugin:
https://github.com/AnthropologieBiblique/link-heading-range/issues/2

Thanks!
ACE

**Comment by rmellmer** [comment]
Howdy! Sorry it's not working for you, honestly I'm pretty new to the whole Obsidian plugin thing so not totally sure why it's not working, everything you've posted appears to be correct. A few questions for troubleshooting:

- What version of Obsidian are you running?
- Does it show up correctly in reader mode?
- Is the link hover functionality working?

**Comment by acepelon** [comment]
Tried on both a Macbook M1 Pro and Macbook M1 Max (although wouldn't expect a difference, these are the only 2 machines I have available).

- Version 1.1.16 (Installer 0.15.9)

- It does not show up correctly in reader mode.

- Hover over is actually working properly I believe but embedded gives me that error:

![image](https://user-images.githubusercontent.com/954789/226212785-808adf77-6af3-4437-bc85-968f84967a3a.png)

---

no hover:
![image](https://user-images.githubusercontent.com/954789/226212792-af020bd0-24f2-4be3-bbb9-d3247ddf4d2f.png)

---
hover:
![image](https://user-images.githubusercontent.com/954789/226212816-0eb87fc8-07de-4bcc-8c69-e97282ef9704.png)

**Comment by rmellmer** [comment]
Makes me wonder if the plugin is conflicting with another plugin or perhaps a theme or something. I haven’t tried it alongside the Strange New Worlds integration, I might need to look into trying that to see if it causes any issues with this plugin.

**Comment by acepelon** [comment]
No worries- we can close if it works for everyone else.  

Take care!
ACE
