### ISSUE TITLE
Plugin not updating

### ISSUE THREAD

**Issue by ParkerRobb** [rmellmer/obsidian-link-range#5]
Obsidian (v1.3.4) shows that I have version 0.1.0 installed (see image below). When I click the "Update" button Obsidian appears to install an update and then says the plugin is now up-to-date, however the installed version never changes from 0.1.0. I installed version 1.0.0 through the Obsidian community plugin portal, so I do not know where it is getting v0.1.0; I have never installed it through BRAT. I've tried uninstalling and reinstalling the plugin to no avail.

![image](https://github.com/rmellmer/obsidian-link-range/assets/62605621/d2e18727-9062-4f89-80ed-7997f909691a)

I am also missing the "Alt Text Format" and "End Inclusive" options in the plugin settings, and links are defaulting to displaying as `note > h1..h2`: 

![image](https://github.com/rmellmer/obsidian-link-range/assets/62605621/df817202-c49a-42a9-8c01-6368e7b2a62e)

**Comment by rmellmer** [comment]
Hi!

Thanks for letting me know, I'll investigate why it's stuck at an older version.

**Comment by rmellmer** [comment]
Ok I just rebuild and updated the plugin. If you could try updating it again you should pull the latest now.

Thanks!

**Comment by ParkerRobb** [comment]
Works as expected now. Thanks for the super quick response!
