### ISSUE TITLE
Alt Text Format for "regular" non-ranged links

### ISSUE THREAD

**Issue by ParkerRobb** [rmellmer/obsidian-link-range#6]
It's great that this plugin reformats ranged links according to what's specified in the Alt Text Format setting, however I noticed it does not reformat "regular" non-ranged links of the format `[[NoteName#h1]]`. Would it be possible to extend the alternate formatting to regular links too?

**Comment by rmellmer** [comment]
Good question, I actually recently had the same thought as well! I’m planning on looking into this, but definitely should be doable! I’ll update this issue when I get around to implementing that!

**Comment by rmellmer** [comment]
This has been resolved in the latest 2.0.0 release
